CREATE TYPE gdps_status AS ENUM ('approved', 'pending', 'rejected');

CREATE TABLE users (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(25) NOT NULL UNIQUE,
    "ip" INET NOT NULL,
    "youtube" VARCHAR(30),
    "github" VARCHAR(39),
    "telegram" VARCHAR(32),
    "createdOn" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE gdps (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner" BIGINT NOT NULL REFERENCES users("id") ON DELETE RESTRICT,
    "name" VARCHAR(25) NOT NULL,
    "description" TEXT,
    "discord" VARCHAR(32),
    "telegram" VARCHAR(32),
    "pc" TEXT,
    "android" TEXT,
    "macos" TEXT,
    "ios" TEXT,
    "trailer" VARCHAR(11),
    "logo" BIGINT,
    "banner" BIGINT,
    "tags" TEXT[],
    "status" gdps_status NOT NULL DEFAULT 'pending',
    "database" TEXT,
    "createdOn" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);